apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: my-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: my-nginx
        env:
          - name: NGINX_INSTANCE
            value: nginx1
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
        resources: {}
      volumes:
        - name: secret-volume
          secret:
            secretName: nginx-pass  
status: {}
