apiVersion: v1
kind: Service
metadata:
  name: logpublish
  labels:
    run: logpublish
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: logpublish
