apiVersion: v1
kind: Service
metadata:
  name: logpublish
  labels:
    run: logpublish
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30080
  selector:
    app: logpublish
